-- MySQL Script generated by MySQL Workbench
-- Dom 21 Jan 2018 17:54:30 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema syncdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `syncdb` ;

-- -----------------------------------------------------
-- Schema syncdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `syncdb` DEFAULT CHARACTER SET utf8 ;
USE `syncdb` ;

-- -----------------------------------------------------
-- Table `device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(48) NOT NULL,
  `offset` BIGINT NULL DEFAULT NULL COMMENT 'Last server offset that was synced',
  `synced` INT NULL DEFAULT NULL COMMENT 'Last timestamp that device was synced',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mapper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mapper` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `table` VARCHAR(45) NOT NULL COMMENT 'Table of new row',
  `from` INT NOT NULL COMMENT 'Row id from origem device',
  `to` INT NOT NULL COMMENT 'Local row id',
  PRIMARY KEY (`id`),
  INDEX `device_id_table_from` (`device_id` ASC, `table` ASC, `from` DESC),
  INDEX `fk_mapper_device_id_idx` (`device_id` ASC),
  CONSTRAINT `fk_mapper_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logger` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `table` VARCHAR(45) NOT NULL COMMENT 'Table that row was modified',
  `row` INT NOT NULL COMMENT 'Row id modified',
  `event` ENUM('insert', 'update', 'delete') NOT NULL COMMENT 'That happens to row',
  `date` INT NOT NULL COMMENT 'Date and time unix timestamp of occurrency',
  PRIMARY KEY (`id`),
  INDEX `fk_logger_device_id_idx` (`device_id` ASC),
  INDEX `table_row` (`table` ASC, `row` DESC),
  CONSTRAINT `fk_logger_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phone_customer_id_idx` (`customer_id` ASC),
  UNIQUE INDEX `uk_phone_custimer_id_number` (`customer_id` ASC, `number` ASC),
  CONSTRAINT `fk_phone_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `customer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `system` (
  `id` ENUM('1') NOT NULL DEFAULT '1',
  `device_id` INT NOT NULL,
  `db_version` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_system_device_id_idx` (`device_id` ASC),
  CONSTRAINT `fk_system_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
